print("===== DESAFIO 02 =====")
Dia = input("Que dia você nasceu? ")
Mês = input("Que mês você nasceu? ")
Ano = input("Que ano você nasceu? ")
print("Você nasceu no dia" ,Dia, "de" ,Mês, "de" ,Ano, "." " Correto? ") 
